# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- main

name: 0.9.$(Rev:.r)

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/tags/v1.2

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: elephant-test-nuget    
    type: dotnet
    to: nuget
    nugetServiceConnection: TestNuget  
    includeSymbols: true
