# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- main
- beta/*

name: 0.10$(Rev:.r)
pool:
  vmImage: 'windows-latest'

variables:
- name: SkipDecorator
  value: true 
- name: checkmarxName
  value: Elephant

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/tags/v1.4.30

extends:
  template: template-pipeline.yml@templates    
  parameters:   
    skipSonarBranch: true
    skipSast: false
    sastFilter: "!**/**, src/**/*" 
    packagename: elephant    
    type: dotnet
    to: nuget
    nugetServiceConnection: Nuget.org Take  
    includeSymbols: true
    testParameters: --configuration Release --no-build --filter "Category=Memory"
